### ISSUE TITLE
Any plans to support AWS ?

### ISSUE THREAD

**Issue by steven-cuthill-otm** [riezebosch/vsts-tasks-packer#1]
support for aws ? we basically need to just swap out the auth method

**Comment by riezebosch** [comment]
Yeah, for sure! Didn't have the need yet but if you could help me out.

**Comment by riezebosch** [comment]
Working on it. Please, [give it a shot](https://github.com/riezebosch/vsts-tasks-packer/releases/tag/0.1.9) and leave some feedback if it works.
