### ISSUE TITLE
Latest commit ba6fc233dcb8796362dca966168bc9d5a98362e4 not made its way to the MarketPlace

### ISSUE THREAD

**Issue by jmos5156** [riezebosch/vsts-tasks-packer#11]
I'm running seemingly version 1.* of your packer extension in Azure Devops but the list of Output variables present in the task and that I can output are not the same as those listed in the last commit ba6fc233dcb8796362dca966168bc9d5a98362e4.

Have you been able to successfully package this commit to the marketplace? 

I kinda rely on this feature update being available really really urgently...

**Comment by jmos5156** [comment]
Is there any response to this question? Would be good to know if there is a plan to get this change into the market place...

**Comment by riezebosch** [comment]
Now it is.

**Comment by jmos5156** [comment]
Hi Manuel.
Many thanks for this. What I've done in the interim is hack your artifact and amend the bits that would allow for the packer output to be used. I've added this to my Azure DevOps as a private install but have I've found a couple more. I'll PR and send to you for review in the normal manner.
