### ISSUE TITLE
Commit 3aa892a

### ISSUE THREAD

**Issue by jmos5156** [riezebosch/vsts-tasks-packer#14]
This is regarding the last commit 3aa892a made into master. I can see that this was a successful build but in Azure DevOps I'm not seeing any update to the output variables of a build task.

I have deleted and recreated the task and job in AzD.

Is there anything else I should be doing to get this update through?

Regards

**Comment by riezebosch** [comment]
You mean it is not visible in the UI?

**Comment by jmos5156** [comment]
Probably not... but my OCD has kicked in and I submitted a new PR https://github.com/riezebosch/vsts-tasks-packer/pull/15/commits/7c50f1286756ff3769658919f7a0fec00979d0f4

Sorry about all this hassle :(
