### ISSUE TITLE
Not all Output Variables are detected from stdout

### ISSUE THREAD

**Issue by jmos5156** [riezebosch/vsts-tasks-packer#16]
Let me start by saying I'm not a developer, nor profess to be one that knows Typescript/Javascript :). So apologies if I'm talking rubbish.

I have tried running the Packer build (latest version) process several times now and keep getting mixed results.
Although the process runs, and completes, not all the output variables are picked up and therefore cannot be used in downstream tasks.

Using Packer 1.5.5 and creating a managed image, packer will output the following to the console 
```
OSType: Windows
ManagedImageResourceGroupName: packervs2019
ManagedImageName: packer-2020-04-17-16.54.42-Basic-jm004
ManagedImageId: /subscriptions/<SUBSCRIPTION_GUID>/resourceGroups/packervs2019/providers/Microsoft.Compute/images/packer-2020-04-17-16.54.42-Basic-jm004
ManagedImageLocation: westeurope
```
 Looking at the source code _vsts-tasks-packer/Packer/PackerV1/src/packer.ts_ the process reads in the stdout from the packer process and runs a simple regex pattern matching to create VSO variables

```
export function addListeners(tool: EventEmitter) {
    tool.addListener('stdout', _ => extractVariable(_.toString()));

    function extractVariable(m: string) {
        let match = m.match(/(OSDiskUri|OSDiskUriReadOnlySas|TemplateUri|TemplateUriReadOnlySas|AMI|ManagedImageId|ManagedImageName|ManagedImageResourceGroupName|ManagedImageLocation|ManagedImageSharedImageGalleryId): (.*)/);
        if (match) {
            tlext.setVariable(match[1], match[2]);
        }

        match = m.match(/ -> (DeploymentName)    : '(.*)'/);
        if (match) {
            tlext.setVariable(match[1], match[2])
        }
    }
}
```
So far I believe to have this correct, but cannot see why the process will not _**match**_ all the variables seen in the regex against the stdout. 

I have copied the console output and used online regex testers to simulate the pattern matching and that seems to work fine.

In my pipeline, I run a Powershell task that outputs the environmental variables of the agent and writes to console the output variables from the Packer Build task. This is where the process fails with:

```
ManagedImageResourceGroupName : packervs2019
ManagedImageName : packer-2020-04-17-16.54.42-Basic-jm004
PackerBuild.ManagedImageLocation : The term 'PackerBuild.ManagedImageLocation' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At D:\a\_temp\4e5e9e8c-f5ab-420f-a2bf-729ec143ff0a.ps1:9 char:38
+ ... rite-Host ManagedImageLocation :  $(PackerBuild.ManagedImageLocation)
```

From the output I see that not all the output variables are listed in the env variables nor do they output by calling the VSO variable name.

This isn't the sole error and it will randomly miss the outputs without rhyme or reason. On rare occasions, it will all work.

Not sure if there is anything we can do, but I had thought of breaking the regex down to say :

```
export function addListeners(tool: EventEmitter) {
    tool.addListener('stdout', _ => extractVariable(_.toString()));

    function extractVariable(m: string) {
        let match = m.match(/(OSDiskUri|OSDiskUriReadOnlySas|TemplateUri|TemplateUriReadOnlySas|AMI): (.*)/);
        if (match) {
            tlext.setVariable(match[1], match[2]);
        }

        match = m.match(/ManagedImageId|ManagedImageName|ManagedImageResourceGroupName|ManagedImageLocation): (.*)/);
       if (match) {
           tlext.setVariable(match[1], match[2]) 
       }
        match = m.match(/ -> (DeploymentName)    : '(.*)'/);
        if (match) {
            tlext.setVariable(match[1], match[2])
        }
    }
}
```
just to break the pattern matching apart in case javascript was not fulfilling all of the pattern matching for some weird reason.

I'm not sure how else I can test this locally but I am willing to help/test where I can.

**Comment by riezebosch** [comment]
I'm afraid that this is due to the fact that the output is delivered in chunks and you have no way to control that other than capturing everything. Probably your output variables are now cut in half and delivered in subsequent chunks making the pattern matching fail.

**Comment by riezebosch** [comment]
The problem was the other way around. There were multiple variables in the same chunk and I was only outputting the first match. Should be fixed by now.

https://github.com/riezebosch/vsts-tasks-packer/commit/547e8bc4f3f96aa6a22b157c5bb78857ca175d04

**Comment by jmos5156** [comment]
I tried to solve this myself and used this code to split the output. It works but maybe not as elegant as your solution. This was me hacking out the extension to attempt to see what was wrong.
```
function addListeners(tool) {
    tool.addListener('stdout', _ => extractVariable(_.toString()));
    function extractVariable(m) {
        //console.log("This is the output of stdout ["+m.toString()+"]");
        let arr = m.toString().trim().split(/\r?\n/);
        //console.log(arr);
        arr.forEach(n => {
            //console.log("--->", n);
            let match = n.match(/(OSDiskUri|OSDiskUriReadOnlySas|TemplateUri|TemplateUriReadOnlySas|AMI): (.*)/);
            if (!match) {
                match = n.match(/(ManagedImageId|ManagedImageName|ManagedImageResourceGroupName|ManagedImageLocation): (.*)/);
            }
            if (!match) {
                match = n.match(/ -> (DeploymentName)    : '(.*)'/);
            }
            if (match) {
                tlext.setVariable(match[1], match[2])
            } else {
                console.log("No match found")
            }
            //console.log("match --->", match);
        });
    }
}
```

but yes you're right. This was down to the way packer outputs stdout and the fact that multiple variables could be output together.
