### ISSUE TITLE
Migration to Node 10 execution handler

### ISSUE THREAD

**Issue by stefanes** [riezebosch/vsts-tasks-packer#21]
The task has recently started warning about Node 6 being removed on March 31st 2022.
Full warning message:
`##[warning]This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.`

Task details:
```
Task         : Packer Tool Installer
Description  : Finds or Downloads and caches specified version spec of Packer and adds it to the PATH.
Version      : 0.146.1876
Author       : Manuel Riezebosch
Help         : [More information](https://packer.io)
```

Related:
- https://github.com/microsoft/azure-pipelines-tasks/issues/15493
- https://aka.ms/migrateTaskNode10

**Comment by riezebosch** [comment]
Fixed: https://github.com/riezebosch/vsts-tasks-packer/commit/61f1420af76e02e0943be1dd1daecdc2f03851eb
