### ISSUE TITLE
Certificate has expired 

### ISSUE THREAD

**Issue by jlangford9284** [riezebosch/vsts-tasks-packer#22]
When trying to use the packertool in azure devops no matter what version we are faced with

Starting: Install Packer 1.8.0
==============================================================================
Task         : Packer Tool Installer
Description  : Finds or Downloads and caches specified version spec of Packer and adds it to the PATH.
Version      : 0.146.1876
Author       : Manuel Riezebosch
Help         : [More information](https://packer.io/)
==============================================================================
Downloading: https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_windows_amd64.zip
##[error]certificate has expired
Finishing: Install Packer 1.8.0

**Comment by SandyB29** [comment]
We have also started facing the same issue in our ADO pipelines.

**Comment by FiggyRoll** [comment]
Same issue started for us last night as well

**Comment by riezebosch** [comment]
I'm afraid it is the download url at hashicorp where the certificate is expired

**Comment by FiggyRoll** [comment]
Is it?, if you check the URL without the filename then the cert is valid, ie.

https://releases.hashicorp.com/packer/1.8.0/

curl'ing both show the cert to be valid as well

```
curl https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip -vI
curl https://releases.hashicorp.com/packer/1.8.0 -vI
```

**Comment by paulgdunnAVEVA** [comment]
This started failing for us as well.  How can we get this resolved?  Seems like the issue resides on the releases.hashicorp.com site.

attached shows that you can emulate the issue in Chrome.  File gets downloaded, but connection is showing "not secure"

![releases hashicorp com Not Secure](https://user-images.githubusercontent.com/90933422/170547005-2e38d061-b05a-4005-a358-8c18ffbcda8b.png)
.

**Comment by paulgdunnAVEVA** [comment]
I also submitted the issue through the Hashicorp.com website. 

![releases hashicorp com Not Secure_2](https://user-images.githubusercontent.com/90933422/170551144-ccce16dc-4fcf-480d-bf81-27d7227296d4.png)

**Comment by jlangford9284** [comment]
> Reference in n

can confirm this is working for us as a work around

**Comment by riezebosch** [comment]
Is it resolved? Looks like working:

```
Starting: Use Packer 
==============================================================================
Task         : Packer Tool Installer
Description  : Finds or Downloads and caches specified version spec of Packer and adds it to the PATH.
Version      : 0.146.1876
Author       : Manuel Riezebosch
Help         : [More information](https://packer.io/)
==============================================================================
Downloading: https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
Extracting archive
/usr/bin/unzip /home/vsts/work/_temp/02ca147b-8ec3-4eb9-9839-0e50091b41b4
Archive:  /home/vsts/work/_temp/02ca147b-8ec3-4eb9-9839-0e50091b41b4
  inflating: packer                  

Caching tool: packer 1.8.0 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/packer/1.8.0/x64
Finishing: Use Packer
```

**Comment by FiggyRoll** [comment]
Its working for us now.
