### ISSUE TITLE
Unable to run PackerTool due to dependency on NodeJS 6

### ISSUE THREAD

**Issue by alexkusuma** [riezebosch/vsts-tasks-packer#35]
Azure DevOps pipelines that uses PackerTool will no longer run, and marked as invalid. This is the error message from AzureDevOps:

The pipeline is not valid. Job validate_template: Step 'PackerTool' references task 'PackerTool' at version '0.146.2019' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator. Job build: Step '' references task 'PackerTool' at version '0.146.2019' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator.

**Note**: Microsoft globally apply the restriction on NodeJS version 6, not me (I'm the admistrator of my azure devops).

**Comment by riezebosch** [comment]
working on it but got the unexpected error now:

```logs
##[error]Aborted
##[warning]Content-Length (16981086 bytes) did not match downloaded file size (16947776 bytes).
```

Seems related: https://github.com/microsoft/azure-pipelines-tasks/issues/18280

I based this task on that one.

**Comment by riezebosch** [comment]
resolved by patching the dependency
