### ISSUE TITLE
Validate command does not properly set variables

### ISSUE THREAD

**Issue by theillien** [riezebosch/vsts-tasks-packer#37]
When running a validation of my packer template, the client_id and client_secret values are not being set properly. They show up as `***` instead of the values in the relevant variable group. I've tried with the values both plain text and marked as secrets.

The command being executed automatically includes these two variables as well as the `subscription_id` and `tenant_id` variables. The latter two are being set correctly (sanitzed below). The error still shows that they are not being set correctly.

```
C:\agent1\_work\_tool\packer\1.10.2\x64\packer.exe validate -var client_id=*** -var client_secret=*** -var subscription_id=<sanitized> -var tenant_id=<sanitized> C:\agent1\_work\41\s\npe-avd-win10.pkr.hcl
Error: Undefined -var variable

A "client_secret" variable was passed in the command line but was not found in
known variables. To declare variable "client_secret", place this block in one of
your .pkr files, such as variables.pkr.hcl

Error: Undefined -var variable

A "subscription_id" variable was passed in the command line but was not found in
known variables. To declare variable "subscription_id", place this block in one
of your .pkr files, such as variables.pkr.hcl

Error: Undefined -var variable

A "tenant_id" variable was passed in the command line but was not found in known
variables. To declare variable "tenant_id", place this block in one of your .pkr
files, such as variables.pkr.hcl

Error: Undefined -var variable

A "client_id" variable was passed in the command line but was not found in known
variables. To declare variable "client_id", place this block in one of your .pkr
files, such as variables.pkr.hcl


##[error]Error: The process 'C:\agent1\_work\_tool\packer\1.10.2\x64\packer.exe' failed with exit code 1
```
I added `client_id=$(variablegroups.PackerVariables.client_id)` and `client_secret=$(variablegroups.PackerVariables.client_secret)` to the Variables field but this did not correct the issue.

I know I can create a variables file but that would defeat the purpose of keeping the client_id and client_secret in a variable group and marked as secrets.

If I am not configuring this properly, what is the correct way?

**Comment by theillien** [comment]
I need some help understanding. I have two variable groups. One is linked to a key vault and contains the service principal ID and secret. These are called principalAppID and principalSecret. I define these in my template as 

````
client_id = "__principalAppID__"
client_secret = "__principalSecret__"
````

Am I supposed to link these to a `client_id` and `client_secret` variable somewhere so the `packer validate` (and `build`) command executes successfully? If not, is it possible to configure the command to use the variables I've defined?

I'm also using the Replace Tokens extension. I have an additional 10 variables defined in my template and the token replacement job passes, but the validation command doesn't use any of them. The validation command will fail if it isn't setting those values.

Do I need to set all of the variables in the Variables field for each of the `validate` and `build` commands instead of using the Replace Tokens extension?

**Comment by riezebosch** [comment]
Sorry for the confusion, most folks use a Service Connection instead of variable groups to provide the client_id and client_secret to the command line.

I wouldn't use token replacement since Packer has built-in support for variables: https://developer.hashicorp.com/packer/guides/hcl/variables

You can use both input variables for your own variables as for the client_id and client_secret. You either grab them from a variable group or a service connection or combine. This extension assumes that when you use a Service Connection you have a `client_id`, `client_secret` and `subscription_id` variable and will add that to the command line.

**Comment by theillien** [comment]
Ah. That's where part of my understanding is breaking down. I am using a service connection which I assume is enabling me to link my key vault to the variable group. When I set the keys in the vault it wouldn't let me use underscores. I could either create a variable with hyphens, e.g. `client-id`, or not use any special characters. I opted for camel-case.

I'll remove the Replace Variables extension from my pipeline and I'll look further into what I need to do to pull the variables in.

Thank you for the information.

**Comment by riezebosch** [comment]
You _can_ use a variable group linked to a key vault, but you also can use a service connection directly for using the service principal for authenticating packer.

**Comment by theillien** [comment]
I'll figure out how to do that. 


Thank you,
Mathew-------- Original Message --------On 3/13/24 18:04, Manuel Riezebosch  wrote:
You can use a variable group linked to a key vault, but you also can use a service connection directly for using the service principal for authenticating packer.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/riezebosch/vsts-tasks-packer/issues/37#issuecomment-1995959607",
"url": "https://github.com/riezebosch/vsts-tasks-packer/issues/37#issuecomment-1995959607",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
