### ISSUE TITLE
Any plans to support Google Cloud?

### ISSUE THREAD

**Issue by reisbel** [riezebosch/vsts-tasks-packer#6]

**Comment by riezebosch** [comment]
Sure thing, if only I knew how to extract those variables.

**Comment by riezebosch** [comment]
Closing for now, happy to add support if someone can tell me what the variable names are that must be extracted from the service connection and which parameter names are most often used in the templates.

**Comment by reisbel** [comment]
See below a working example of your vsts-task with Google Cloud
https://github.com/reisbel/gcp-azuredevops-packer

Please let me know if need any other info.

**Comment by riezebosch** [comment]
Nice! But seems like you need a secrets file and cannot use a service connection for this?

**Comment by reisbel** [comment]
That's right. I uploaded the service account key to Azure DevOps as a Secure File under the Library section and download the file during the build execution.
