### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by mdurell** [riezebosch/vsts-tasks-packer#7]
This is a very handy marketplace item but I can't use this without clarity around licensing. Please clarify your license by adding the appropriate supporting documentation as required by your chosen license.

**Comment by riezebosch** [comment]
https://github.com/riezebosch/vsts-tasks-packer/commit/88eb5f0a88d80662585254ebb2706ee66367bfa0

**Comment by mdurell** [comment]
Thank you for clarifying this and choosing one that happens to be compatible with our corporate standards. And thank you for contributing this valuable work to the community!
